# Generated by Django 4.2.7 on 2023-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default', max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='default', max_length=100, verbose_name='密码')),
            ],
        ),
    ]
