# Generated by Django 4.2.7 on 2023-11-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0002_user_avatar_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='http://localhost:8000/static/avatar/defaultAvatar.jpg', max_length=256, verbose_name='头像'),
        ),
    ]
