# Generated by Django 4.2.7 on 2023-11-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0004_remove_user_avatar_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='http://localhost:8000/static/avatar/defaultAvatar.jpg', max_length=256, verbose_name='头像'),
        ),
    ]
