# Generated by Django 4.2.7 on 2023-11-30 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0005_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='图片名')),
                ('discription', models.CharField(default='这个人很懒，什么都没有留下', max_length=1024, verbose_name='图片描述')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('url', models.CharField(max_length=256, verbose_name='图片url地址')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='discription',
            field=models.CharField(default='这个人很懒，什么都没有留下', max_length=1024, verbose_name='相册描述'),
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myserver.album', verbose_name='相册')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myserver.photo', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myserver.photo', verbose_name='图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myserver.user', verbose_name='用户')),
            ],
        ),
    ]
