# Generated by Django 4.2.7 on 2023-12-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0006_photo_album_discription_photoalbum_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
