# Generated by Django 4.2.7 on 2023-12-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0007_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='forePage',
            field=models.CharField(default='http://localhost:8000/static/images/defaultAlbumForePage.png', max_length=256, verbose_name='封面图片url地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='http://localhost:8000/static/avatars/defaultAvatar.jpg', max_length=256, verbose_name='头像'),
        ),
    ]
